name: Deploy Astro site to GitHub Pages

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22
      - run: npm install
      - run: npx astro build
      - name: Deploy to GitHub Pages
        run: npx astro deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
